//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.Tag = new HashSet<Tag>();
        }
    
        public long commentId { get; set; }
        public long usrId { get; set; }
        public long eventId { get; set; }
        public System.DateTime date { get; set; }
        public string texto { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }

        public override bool Equals(object obj)
        {
            Comment target = (Comment)obj;

            return true
               && (this.commentId == target.commentId)
               && (this.usrId == target.usrId)
               && (this.eventId == target.eventId)
               && (this.texto == target.texto)
               && (this.date.Equals(target.date));

        }

        public override String ToString()
        {
            StringBuilder strUserProfile = new StringBuilder();

            strUserProfile.Append("[ ");
            strUserProfile.Append(" commentId = " + commentId + " | ");
            strUserProfile.Append(" usrId = " + usrId + " | ");
            strUserProfile.Append(" eventId = " + eventId + " | ");
            strUserProfile.Append(" texto = " + texto + " | ");
            strUserProfile.Append("] ");

            return strUserProfile.ToString();
        }

    }
}
