//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    public partial class Tag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tag()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public long tagId { get; set; }
        public string tagName { get; set; }
        public long usedNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }

        public override int GetHashCode()
        {
            unchecked
            {
                int multiplier = 31;
                int hash = GetType().GetHashCode();

                hash = hash * multiplier + tagId.GetHashCode();
                hash = hash * multiplier + (tagName == null ? 0 : tagName.GetHashCode());
                return hash;
            }

        }

        public override bool Equals(object obj)
        {
            Tag target = (Tag)obj;

            return true
               && (this.tagId == target.tagId)
               && (this.tagName == target.tagName);

        }

        public override String ToString()
        {
            StringBuilder strUserProfile = new StringBuilder();

            strUserProfile.Append("[ ");
            strUserProfile.Append(" tagId = " + tagId + " | ");
            strUserProfile.Append(" tagName = " + tagName + " | ");
            strUserProfile.Append("] ");

            return strUserProfile.ToString();
        }

    }
}
