//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    public partial class UserGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserGroup()
        {
            this.UserProfile = new HashSet<UserProfile>();
            this.Recomendation = new HashSet<Recomendation>();
        }
    
        public long groupId { get; set; }
        public string groupName { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recomendation> Recomendation { get; set; }


        public override bool Equals(object obj)
        {
            UserGroup target = (UserGroup)obj;

            return true
               && (this.groupId == target.groupId)
               && (this.groupName == target.groupName)
               && (this.description == target.description);

        }

        public override String ToString()
        {
            StringBuilder strUserProfile = new StringBuilder();

            strUserProfile.Append("[ ");
            strUserProfile.Append(" groupId = " + groupId + " | ");
            strUserProfile.Append(" groupName = " + groupName + " | ");
            strUserProfile.Append(" description = " + description + " | ");
            strUserProfile.Append("] ");

            return strUserProfile.ToString();
        }


    }
}
