//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Web.Pages.User.App_LocalResources.en_default {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateUserProfile_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateUserProfile_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Es.Udc.DotNet.PracticaMaD.Web.Pages.User.App_LocalResources.en_default.UpdateUser" +
                            "Profile.aspx", typeof(UpdateUserProfile_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnUpdate_Text {
            get {
                return ResourceManager.GetString("btnUpdate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lclCountry_Text {
            get {
                return ResourceManager.GetString("lclCountry.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lclEmail_Text {
            get {
                return ResourceManager.GetString("lclEmail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string lclFirstName_Text {
            get {
                return ResourceManager.GetString("lclFirstName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lclLanguage_Text {
            get {
                return ResourceManager.GetString("lclLanguage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile details.
        /// </summary>
        internal static string lclMenuExplanation_Text {
            get {
                return ResourceManager.GetString("lclMenuExplanation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string lclSurname_Text {
            get {
                return ResourceManager.GetString("lclSurname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string lnkChangePassword_Text {
            get {
                return ResourceManager.GetString("lnkChangePassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PracticaMaD - Update User Profile.
        /// </summary>
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email syntax.
        /// </summary>
        internal static string revEmail_ErrorMessage {
            get {
                return ResourceManager.GetString("revEmail.ErrorMessage", resourceCulture);
            }
        }
    }
}
